# This workflow will combine all scripts under /algorithm into a single file.

name: Web bundler

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  build-bundles:
    name: Build the bundles
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: test-workflow
    - name: Build web bundle
      run: cat ./algorithm/* | grep -v '"use strict";' > ./holo-cube-algorithm.web-bundle.js
    - name: Publish web bundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: holo-cube-web-bundle
        path: ./holo-cube-algorithm.web-bundle.js
  merge-to-release:
    name: Merge to release branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: release
    - name: Merge test-workflow into release locally
      run: git merge test-workflow
    - name: Commit the merge
      run: git commit -m "Auto-merge to release"
    - name: Push the merge
      run: git push
  push-artifact:
    name: Push artifact to release branch
    needs: [build-bundles, merge-to-release]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: release
    - name: Download web bundle artifact
      uses: actions/download-artifact@v3
      with:
        name: holo-cube-web-bundle
        path: ./bundles/holo-cube-algorithm.web-bundle.js
    - name: Push bundles to release
      run: git add ./bundles/.; git commit -m "Auto-update bundles"; git push

  
  
