# This workflow will combine all scripts under /algorithm into a single file.

name: Web bundler

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  bundle:
    name: Web bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cat and remove use stricts
      run: cat ./algorithm/* | grep -v '"use strict";' > ./bundles/web/holo-cube-algorithm.bundle.js
    - name: Show bundle
      run: cat holo-cube-algorithm.web-bundle.js
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: holo-cube-web-bundle
        path: ./bundles/web/holo-cube-algorithm.web-bundle.js
