# This workflow will combine all scripts under /algorithm into a single file.

name: Web bundler

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  bundle:
    name: Web bundle
    runs-on: ubuntu-latest
    env:
      WebBundlePath: ./bundles/holo-cube-algorithm.web-bundle.js
      NodeBundlePath: ./bundles/holo-cube-algorithm.node-bundle.js
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cat and remove use stricts
      run: cat ./algorithm/* | grep -v '"use strict";' > $WebBundlePath
    - name: Display bundle path
      run: echo $WebBundlePath
    - name: Show bundle
      run: cat $WebBundlePath
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: holo-cube-web-bundle
        path: ./bundles/holo-cube-algorithm.web-bundle.js
