# This workflow will combine all scripts under /algorithm into a single file.

name: Web bundler

on:
  push:
    branches: [ "test-workflow" ]

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Show path
      run: pwd
    - name: Show directory
      run: ls -l -a
    - name: Cat and remove use stricts
      run: cat ./algorithm/* | grep -v '"use strict";' > holo-cube-algorithm.bundle.js
